#!/bin/bash
#SBATCH -D /home/guglib/bitbucket/nf/toy_example/work/1d/db1c1c8374dcbf219965d22e3aea3e
#SBATCH -J nf-quant_(2)
#SBATCH -o /home/guglib/bitbucket/nf/toy_example/work/1d/db1c1c8374dcbf219965d22e3aea3e/.command.log
#SBATCH --no-requeue
# NEXTFLOW TASK: quant (2)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /home/guglib/bitbucket/nf/toy_example/work/1d/db1c1c8374dcbf219965d22e3aea3e/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && kill $pid 2>/dev/null
}

nxf_launch() {
    set +u; env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} singularity exec /home/guglib/cache/quay.io-biocontainers-rsem-1.3.3--pl5262h3198e80_2.img /bin/bash -c "cd $PWD; /bin/bash -ue /home/guglib/bitbucket/nf/toy_example/work/1d/db1c1c8374dcbf219965d22e3aea3e/.command.sh"
}

nxf_stage() {
    true
    # stage input files
    rm -f SRR1641108.1_R1_paired.fastq
    rm -f SRR1641108.1_R1_unpaired.fastq
    rm -f SRR1641108.1_R2_paired.fastq
    rm -f SRR1641108.1_R2_unpaired.fastq
    ln -s /home/guglib/bitbucket/nf/toy_example/work/1c/663aa601baf3f833aa87007487864b/SRR1641108.1_R1_paired.fastq SRR1641108.1_R1_paired.fastq
    ln -s /home/guglib/bitbucket/nf/toy_example/work/1c/663aa601baf3f833aa87007487864b/SRR1641108.1_R1_unpaired.fastq SRR1641108.1_R1_unpaired.fastq
    ln -s /home/guglib/bitbucket/nf/toy_example/work/1c/663aa601baf3f833aa87007487864b/SRR1641108.1_R2_paired.fastq SRR1641108.1_R2_paired.fastq
    ln -s /home/guglib/bitbucket/nf/toy_example/work/1c/663aa601baf3f833aa87007487864b/SRR1641108.1_R2_unpaired.fastq SRR1641108.1_R2_unpaired.fastq
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A)"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/guglib/bitbucket/nf/toy_example/work/1d/db1c1c8374dcbf219965d22e3aea3e/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    local ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
